//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoporteTech.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTicket
    {
        public int HistorialID { get; set; }
        public int TicketID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
        public string EstadoAnterior { get; set; }
        public string EstadoNuevo { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
