//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoporteTech.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.HistorialTickets = new HashSet<HistorialTicket>();
        }
    
        public int TicketID { get; set; }
        public int ClienteID { get; set; }
        public int EquipoID { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> TecnicoID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Equipos Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialTicket> HistorialTickets { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
